//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetyraMVC_Programimi_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Attendance
    {
        [Required]
        public int AttendanceID { get; set; }

        [Required]
        public Nullable<int> StudentID { get; set; }

        [Required]
        public Nullable<int> SubjectID { get; set; }

        [Required]
        public Nullable<System.DateTime> Date { get; set; }

        [Required]
        public Nullable<bool> Status { get; set; }
    }
}
