//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetyraMVC_Programimi_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Class
    {
        [Required]
        public string ClassID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public Nullable<int> StudentID { get; set; }

        [Required]
        public Nullable<int> TeacherID { get; set; }
    }
}
