//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetyraMVC_Programimi_WEB.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Enrollment
    {
        [Required]
        public string EnrollmentID { get; set; }

        [Required]
        public string EnrollmentDate { get; set; }


        [Required]
        public string CourseID { get; set; }

        [Required]
        public string StudentID { get; set; }


        [Required]
        public string ClassID { get; set; }

        [Required]
        public string Grade { get; set; }
    }
}
