//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetyraMVC_Programimi_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        [Required]
        public int StudentID { get; set; }

        [Required]
        public string FirstName { get; set; }


        [Required]
        public string FatherName { get; set; }


        [Required]
        public string LastName { get; set; }

        [Required]
        public Nullable<System.DateTime> Birthdate { get; set; }


        [Required]
        public string Address { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public Nullable<int> PhoneNo { get; set; }

        [Required]
        public string Email { get; set; }
    }
}
